[project]
name = "system-info-collector"
version = "1.2.3"
description = "Advanced system information collection and reporting utility"
authors = [{name = "DataSystems", email = "info@datasys.com"}]
license = {text = "MIT"}
requires-python = ">=3.6"
keywords = ["system", "information", "monitoring", "reporting"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: System Administrators", 
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: System :: Monitoring"
]

dependencies = [
    "requests>=2.25.0",
    "psutil>=5.8.0", 
    "cryptography>=3.4.0"
]

[project.urls]
homepage = "https://github.com/datasystems/system-info-collector"
repository = "https://github.com/datasystems/system-info-collector.git"
documentation = "https://datasys.com/docs/system-info"

[project.scripts]
system-info = "system_info_collector:main"

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"
